import "./globals.css";
import Header from "@/components/Header";
import { HiddenMask, HiddenMasksHelper, TooltipProvider } from "@/components/ui";
import clsx from "clsx";
import { fonts } from "@/lib/fonts";

export const metadata = {
  title: "Lila Rest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <HiddenMasksHelper />
      <body className={clsx(fonts, "dark bg-reveal reveal")}>
        <TooltipProvider delayDuration={400}>
          <HiddenMask pattern="tiny" />
          <div className="min-h-screen max-w-screen">
            <Header />
            <main>{children}</main>
            {/* <Footer /> */}
          </div>
        </TooltipProvider>
      </body>
    </html>
  );
}
