import "./globals.css";
import Header from "@/components/Header";
import { HiddenMasksHelper, TooltipProvider } from "@/components/ui";
import clsx from "clsx";
import { fonts } from "@/lib/fonts";

export const metadata = {
  title: "Lila Rest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <HiddenMasksHelper />
      <body className={clsx(fonts, "dark")}>
        <TooltipProvider delayDuration={400}>
          <Header />
          <main>{children}</main>
          {/* <Footer /> */}
        </TooltipProvider>
      </body>
    </html>
  );
}
